### ISSUE TITLE
diderot-admin

### ISSUE THREAD

**Issue by umutacar** [diderot-edu/diderot-cli#12]
I got stuck when trying to update a chapter.  I used the command incorrectly but there was no "help".

```
bash-3.2$ admin/diderot_admin 
admin/diderot_admin 
Username: ..
Password: ..
Successfully logged in to Diderot.
DiderotCLI >> help
help

Documented commands (type help <topic>):
========================================
EOF                  help              list_courses       update_assignment
download_assignment  list_assignments  quit               update_book      
exit                 list_books        submit_assignment

DiderotCLI >> update_book guide mtl --xml ~/diderot/guide/mtl/mtl.xml 
update_book guide mtl --xml ~/diderot/guide/mtl/mtl.xml 
Failure uploading book.
DiderotCLI >> help update_book
help update_book
```

**Comment by rohany** [comment]
I am still in the process of giving update_book and update_assignment  descriptive errors. I'm working right now on fixing up the help messages, as there is a little disparity between the help vs parser help.

Turns out there is a lot of work when turning something from a personal tool into a tool usable by hundreds of students :D

**Comment by rohany** [comment]
#13 (which just landed), should make sure that you get help messages for all the commands now.

**Comment by rohany** [comment]
#16 gives proper help/error output for the update_book command now.
