### ISSUE TITLE
Support reading credentials based off of an environment variable

### ISSUE THREAD

**Issue by rohany** [diderot-edu/diderot-cli#37]
Similar to AWS, we put the path to a credentials file in an environment variable, or we can expect it to always be in a place?

Such as `~/.diderot/credentials`

**Comment by umutacar** [comment]
If we are going to store the credentials, especially the password in a text file, why not hash, more correctly encode it?  All we need is for the diderot authentication to decode the password before checking.  Because this happens on the server, it would be safe.

**Comment by rohany** [comment]
We aren’t storing any credentials — this is if a user wants to put their credentials in a local file rather then passing them to the cli via args or logging in.

**Comment by umutacar** [comment]
Doesn't that mean that "we" are storing credentials (the user might stor their password in clear text in some file)?

**Comment by rohany** [comment]
I guess we are -- though AWS CLI does exactly this for credentials. I'm not sure how to encode/decode the credentials without registering some sort of private key on diderot though.

**Comment by rohany** [comment]
I take it back -- AWS CLI does something slightly different -- it gives you two tokens that you can use and place in a text file. I _think_ these tokens can be nullified so it is safer than this.

**Comment by umutacar** [comment]
AWS CLI stores the public key on a file and private on the server.  I would think that python has a way of encoding/decoding passwords, which should be a pretty standard thing.

**Comment by rohany** [comment]
I think we could have a command that generates a credentials file from the users current session, encoding the credentials as bytes in a file. It could then read the file when a credentials file is specified.

**Comment by umutacar** [comment]
That might work.

**Comment by rohany** [comment]
Another option is to just move towards token authentication like Ryan suggested in another issue. After logging in once, users receive a token. After receiving this token they can place it in a file and don't need to give their credentials anymore.

**Comment by umutacar** [comment]
I am not familiar with token based authentication.

(A 10-second read suggests that this is primarily designed for situations
where you share your credentials to give another application access to a
resource. The example that comes to mind various financial apps asking you
to log into your bank account from their server  so that they can pull some
info such as your expenses.  all they need is a temporary token but they
take your password.  we don't seem to have the same concern here (we are
not asking the user to provide us a pass for another app).)

-- Umut
