### ISSUE TITLE
Add an admin mode to diderot cli

### ISSUE THREAD

**Issue by rohany** [diderot-edu/diderot-cli#7]
Checks your login authentication -- if you aren't a staff or ta member command fails.

**Comment by rohany** [comment]
@umutacar what do you think is a better solution?
- Maintaining a separate CLI that has admin commands, and this CLI is only available to TA's / instructors
- Allowing admin commands to be present in the student accesible CLI, but those commands only succeed if the user has permission to execute said commands.

**Comment by umutacar** [comment]
Good question.  I like the security of having two separate ones but then it is inconvenient to maintain two code bases.  

How about this:  we have  a single source but we compile two versions, one for TAs and one fo students.  The student versions simply don't have the admin commands but otherwise the two are called the same, e.g.,

``` 
$ did submit skyline.sml 
$ did upload chapter_sequences
```
Upload available is an option for TAs.  They would both need authentication of course.

**Comment by rohany** [comment]
Given that the codebase is in python, how do we compile two separate versions of the CLI? Ideally we could just have a macro/ifdef including some code or not, but I don't know how to do that in python.

**Comment by umutacar** [comment]
ohh good point.  python is terrible for compling and for extracting an
executable.  let me think about it....

one idea would be to write the code so that there is a simple wrapper
"driver" for students and one for staff, that pulls the relevant
packages.  ideally, other than just a few lines of code, the two
drivers would be idential, with the one for TA's including the admin
package.

-- Umut

**Comment by rohany** [comment]
I have a class that implements the CLI -- i could have another CLI Class that inherits from it (the student CLI), and then provides extra functionality?

**Comment by umutacar** [comment]
good idea!

-- Umut

**Comment by rohany** [comment]
yup, that worked.
