### ISSUE TITLE
improved testing for the CLI

### ISSUE THREAD

**Issue by rohany** [diderot-edu/diderot-cli#94]
TLDR: We should deprecate this test server and move to writing Django tests.

Bojan had a great insight that when running tests in this repository _inside_ the Diderot repository, we get access to the Django server's testing utilities. Using these, we can hit specific endpoints and then inspect state within Diderot. This form of testing will allow us to write better tests, and also exercise more functionality within Diderot.

**Comment by bojanbg** [comment]
Thank you for the write up Rohan. While working on `diderot-cli`, I came up with an idea for tests that are almost integration-level, but that don't need the fake web-server running. There was no time for me to implement it, but I can briefly describe it here:

It centers on a change to `DiderotClient` to specify (or switch) which client we want to use. For regular use, we stay with `requests` from the standard library. For tests, we use DRF's `APIClient`.

We also need a way add a parameter to `DiderotUser` and `DiderotAdmin` constructors that will ultimately be passed to `DiderotClient` to specify which to use (with `requests` remaining the default). Then, we can simply modify `runUserCmd` and `runAdminCmd` in `test.py` use the test client.

This way if the tests are ran from the `src` directory, we will be testing argument parsing, routing and business logic. Only the HTTP round-trip stuff would remain untested (because there isn't an actual server it goes to), but I don't think there's much need or value in testing this.
